package com.gestel.applicagestel.model;
// Generated 14 juil. 2015 15:21:25 by Hibernate Tools 3.2.1.GA


import java.util.Collection;
import java.util.*;
import java.util.Set;
import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;
/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name="departement"
    ,catalog="maventelgest"
)
public class Departement  implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="IDDEPARTEMENT", unique=true, nullable=false)
     private Integer iddepartement;
    @Column(name="DEPARTEMENT_NAME", length=15)
     private String departementName;
     //@OneToMany(fetch=FetchType.EAGER,cascade= CascadeType.ALL)
     //@JoinColumn(name="iddepartment")
    @OneToMany(fetch = FetchType.EAGER,mappedBy = "departement",cascade= CascadeType.PERSIST)
     private List<Employee> employees;

    public Departement() {
    }

	
    public Departement(Integer iddepartement) {
        this.iddepartement = iddepartement;
    }
    public Departement(Integer iddepartement, String departementName) {
       this.iddepartement = iddepartement;
       this.departementName = departementName;
    }

    public Departement(String departementName) {
        this.departementName = departementName;
    }
   
         public Integer getIddepartement() {
        return this.iddepartement;
    }
    
    public void setIddepartement(Integer iddepartement) {
        this.iddepartement = iddepartement;
    }
    
        public String getDepartementName() {
        return this.departementName;
    }
    
    public void setDepartementName(String departementName) {
        this.departementName = departementName;
    }

    public List<Employee> getEmployees() {
        return employees;
    }

    public void setEmployees(List<Employee> employees) {
        this.employees = employees;
    }

  
  public void addEmployees(Employee employee){
    employee.setDepartement(this);
    employees.add(employee);
   }
    

   

    



}


