package com.gestel.applicagestel.model;
// Generated 14 juil. 2015 15:21:25 by Hibernate Tools 3.2.1.GA


import java.util.Collection;
import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="maventelgest"
)
public class Employee  implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="IDPERSONNE", unique=true, nullable=false)
     private Integer idpersonne;
    // private int iddepartement;
    @Column(name="MATRICULE", length=15)
     private String matricule;
    @Column(name="NOM", length=15)
     private String nom;
    @Column(name="PRENOM", length=15)
     private String prenom;
    @Column(name="FONCTION", length=15)
     private String fonction;
    @Column(name="CIN", length=30)
     private String cin;
    @Column(name="DATEAQUISE", length=15)
     private String dateaquise;
     
    
     @ManyToOne(fetch = FetchType.EAGER,cascade= CascadeType.PERSIST)
     @JoinColumn(name="departement_iddepartement")
    
     private Departement departement;
     
     //@OneToMany(mappedBy="phone")
    @OneToMany(fetch = FetchType.EAGER,mappedBy = "employee",cascade= CascadeType.PERSIST)
    @Fetch(value = FetchMode.SUBSELECT)
     private Collection<Phone> phones;
    
    
    @OneToMany(fetch = FetchType.EAGER,mappedBy = "employee",cascade= CascadeType.PERSIST)
    @Fetch(value = FetchMode.SUBSELECT)
     private Collection<Sim> sims;

    public Employee() {
    }

    public Employee(String matricule, String nom, String prenom, String fonction, String cin, String dateaquise) {
        this.matricule = matricule;
        this.nom = nom;
        this.prenom = prenom;
        this.fonction = fonction;
        this.cin = cin;
        this.dateaquise = dateaquise;
    }

	
    /*public Employee(int iddepartement) {
        this.iddepartement = iddepartement;
    }*/
   
   
         public Integer getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(Integer idpersonne) {
        this.idpersonne = idpersonne;
    }
    
   /* @Column(name="IDDEPARTEMENT", nullable=false)
    public int getIddepartement() {
        return this.iddepartement;
    }
    
    public void setIddepartement(int iddepartement) {
        this.iddepartement = iddepartement;
    }*/
    
        public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    
        public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    
        public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    
        public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    
        public String getCin() {
        return this.cin;
    }
    
    public void setCin(String cin) {
        this.cin = cin;
    }
    
        public String getDateaquise() {
        return this.dateaquise;
    }
    
    public void setDateaquise(String dateaquise) {
        this.dateaquise = dateaquise;
    }

    public Departement getDepartement() {
        return departement;
    }

    public void setDepartement(Departement departement) {
        this.departement = departement;
    }

    public Collection<Phone> getPhone() {
        return phones;
    }

    public void setPhone(Collection<Phone> phone) {
        this.phones = phones;
    }

 public void addPhoneses(Phone phone){
    phone.setEmployee(this);
    phones.add(phone);
   }
  public Collection<Sim> getSim() {
        return sims;
    }

    public void setSim(Collection<Sim> sim) {
        this.sims = sims;
    }

 public void addSims(Sim sim){
    sim.setEmployee(this);
    sims.add(sim);
   }


}


