package com.gestel.applicagestel.model;
// Generated 14 juil. 2015 15:21:25 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Option generated by hbm2java
 */
@Entity
@Table(name="service"
    ,catalog="maventelgest"
)
public class Option  implements java.io.Serializable {

    
     @Id
     @GeneratedValue(strategy= GenerationType.IDENTITY)
     @Column(name="IDSERVICE", unique=true, nullable=false)
     private Integer idservice;
     
    @Column(name="DESCRIPTION", length=30)
     private String description;
    @Column(name="NOM_SERVICE", length=15)
     private String nomService;
    
    //@ManyToMany(cascade= CascadeType.ALL,mappedBy="sims")
    @ManyToMany(mappedBy = "services")
    private Set<Sim> sims =new HashSet<Sim>(0);

    public Set<Sim> getSims() {
        return sims;
    }

    public void setSims(Set<Sim> sims) {
        this.sims = sims;
    }
    
    

    public Option() {
    }

    public Option(String description, String nomService) {
       this.description = description;
       this.nomService = nomService;
    }
   
    
    
        public Integer getIdservice() {
        return this.idservice;
    }
    
    public void setIdservice(Integer idservice) {
        this.idservice = idservice;
    }
    
        public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
        public String getNomService() {
        return this.nomService;
    }
    
    public void setNomService(String nomService) {
        this.nomService = nomService;
    }




}


