package com.gestel.applicagestel.model;
// Generated 14 juil. 2015 15:21:25 by Hibernate Tools 3.2.1.GA


import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name="phone"
    ,catalog="maventelgest"
)
public class Phone  implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="IDPHONE", unique=true, nullable=false)
     private Integer idphone;
     //private int idpersonne;
    @Column(name="MARQUE", length=15)
     private String marque;
    @Column(name="SERIAL", length=30)
     private String serial;
    @Column(name="SERIEPHONE", length=15)
     private String seriephone;
     @ManyToOne(fetch = FetchType.EAGER,cascade= CascadeType.PERSIST)
     @JoinColumn(name="personne_idpersonne")
    
     private Employee employee;
     
    public Phone() {
    }

    public Phone(String marque, String serial, String seriephone) {
        this.marque = marque;
        this.serial = serial;
        this.seriephone = seriephone;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
 
    
    
	
   /* public Phone(int idpersonne) {
        this.idpersonne = idpersonne;
    }*/
   /* public Phone(int idpersonne, String marque, String serial, String seriephone) {
       this.idpersonne = idpersonne;
       this.marque = marque;
       this.serial = serial;
       this.seriephone = seriephone;
    }*/
   
         public Integer getIdphone() {
        return this.idphone;
    }
    
    public void setIdphone(Integer idphone) {
        this.idphone = idphone;
    }
    
   /* @Column(name="IDPERSONNE", nullable=false)
    public int getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(int idpersonne) {
        this.idpersonne = idpersonne;
    }*/
    
        public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }
    
        public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    
        public String getSeriephone() {
        return this.seriephone;
    }
    
    public void setSeriephone(String seriephone) {
        this.seriephone = seriephone;
    }




}


