package com.gestel.applicagestel.model;
// Generated 14 juil. 2015 15:21:25 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Sim generated by hbm2java
 */
@Entity
@Table(name="sim"
    ,catalog="maventelgest"
)
public class Sim  implements java.io.Serializable {

    @Id
    @Column(name="NUMEROTEL", unique=true, nullable=false, length=30)
     
     private String numerotel;
   /* @Column(name="IDPERSONNE", nullable=false)
     private int idpersonne;*/
    @Column(name="SERIESIM", length=30)
     private String seriesim;
    @Column(name="PUK", length=30)
     private String puk;
    @Column(name="PIN", length=30)
     private String pin;
    @Column(name="TYPE", length=30)
     private String type;
    
    @ManyToMany(cascade= CascadeType.PERSIST)
    //@JoinTable(name="activer", joinColumns=@JoinColumn(name="numerotel"), inverseJoinColumns=@JoinColumn(name="idservice")) 
    @JoinTable(name = "activer", joinColumns = { 
			@JoinColumn(name = "numerotel", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "idservice", 
					nullable = false, updatable = false) })
    private Set<Option> services =new HashSet<Option>(0);

    

    public Set<Option> getServices() {
        return services;
    }

    public void setServices(Set<Option> services) {
        this.services = services;
    }
    
    @ManyToOne(fetch = FetchType.EAGER,cascade= CascadeType.PERSIST)
    @JoinColumn(name="IDPERSONNE_SIM")
    
    private Employee employee;
   
    
    public Sim() {
    }

	
 /*   public Sim(String numerotel, int idpersonne) {
        this.numerotel = numerotel;
        this.idpersonne = idpersonne;
    }*/
    public Sim(String numerotel, String seriesim, String puk, String pin, String type) {
       this.numerotel = numerotel;
       //this.idpersonne = idpersonne;
       this.seriesim = seriesim;
       this.puk = puk;
       this.pin = pin;
       this.type = type;
    }
   
         public String getNumerotel() {
        return this.numerotel;
    }
    
    public void setNumerotel(String numerotel) {
        this.numerotel = numerotel;
    }
    
     /*   public int getIdpersonne() {
        return this.idpersonne;
    }*/
    
    /*public void setIdpersonne(int idpersonne) {
        this.idpersonne = idpersonne;
    }*/
    
        public String getSeriesim() {
        return this.seriesim;
    }
    
    public void setSeriesim(String seriesim) {
        this.seriesim = seriesim;
    }
    
        public String getPuk() {
        return this.puk;
    }
    
    public void setPuk(String puk) {
        this.puk = puk;
    }
    
        public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }
    
        public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }




}


